#!/usr/bin/python
# -*- coding: utf-8 -*-

__all__ = ["ATTR_MEMORY_IN_GBS", "ATTR_NUMBER_OF_PORTS", "ATTR_NUMBER_OF_CPUS", "EX_MISSING_ATTRIBUTE",
           "MAXIMUM_ALLOWED_VNICS_ON_CLOUD_PROVIDER", "MAXIMUM_ALLOWED_CPUS_ON_CLOUD_PROVIDER",
           "MAXIMUM_ALLOWED_MEMORY_ON_CLOUD_PROVIDER", "MEMORY_BY_DEFAULT", "NUMBER_OF_OVF_VNICS_BY_DEFAULT",
           "NUMBER_OF_VCPUS_BY_DEFAULT", "WARN_MAXIMUM_CPUS", "WARN_MAXIMUM_MEMORY", "WARN_MAXIMUM_PORTS",
           "WARN_MINIMUM_CPUS", "WARN_MINIMUM_MEMORY", "WARN_MINIMUM_PORTS", "REQUIRED_ATTRIBUTES"
           ]


ATTR_MEMORY_IN_GBS = "Memory in GB"
ATTR_NUMBER_OF_PORTS = "Number of Ports"
ATTR_NUMBER_OF_CPUS = "Number of vCPUs"
EX_MISSING_ATTRIBUTE = "Missing attribute {1} on resource model {0}"
MAXIMUM_ALLOWED_VNICS_ON_CLOUD_PROVIDER = 10
MAXIMUM_ALLOWED_CPUS_ON_CLOUD_PROVIDER = 128
MAXIMUM_ALLOWED_MEMORY_ON_CLOUD_PROVIDER = 4000
MEMORY_BY_DEFAULT = 8
NUMBER_OF_OVF_VNICS_BY_DEFAULT = 2
NUMBER_OF_VCPUS_BY_DEFAULT = 4
WARN_MAXIMUM_CPUS = "warning: IGNORING CONFIGURED NUMBER OF VCPUS={0} VCPUS ON {1}\n MAXIMUM NUMBER OF VPUS IS {2}"
WARN_MAXIMUM_MEMORY = "warning: IGNORING CONFIGURED MEMORY={0} GB ON {1}\n MAXIMUM MEMORY IS {2} GB"
WARN_MAXIMUM_PORTS = "warning: IGNORING CONFIGURED NUMBER OF PORTS={0} ON {1}\n MAXIMUM NUMBER OF PORTS IS {2}"
WARN_MINIMUM_CPUS = "warning: IGNORING CONFIGURED NUMBER OF VCPUS={0} VCPUS ON {1}\n MINIMUM NUMBER OF VPUS IS {2}"
WARN_MINIMUM_MEMORY = "warning: IGNORING CONFIGURED MEMORY={0} GB ON {1}\n MINIMUM MEMORY IS {2} GB"
WARN_MINIMUM_PORTS = "warning: IGNORING CONFIGURED NUMBER OF PORTS={0} PORTS ON {1}\n MINIMUM NUMBER OF PORTS IS {2}"
REQUIRED_ATTRIBUTES = [ATTR_NUMBER_OF_PORTS, ATTR_MEMORY_IN_GBS, ATTR_NUMBER_OF_PORTS]
